### ISSUE TITLE
Why is this marked obselete?

### ISSUE THREAD

**Issue by n2cholas** [MerHS/SASA-pytorch#5]
Thanks so much for writing this implementation @MerHS. Why is it marked obsolete in the description?

**Comment by MerHS** [comment]
Thank you for your attention, but right now, I can't afford to spend time on ML applications, so I can't fix implementation errors in this repository.

Please see [this repo](https://github.com/leaderj1001/Stand-Alone-Self-Attention) if you really interested in this topic.

Thanks.

**Comment by n2cholas** [comment]
@MerHS Thanks!
